import "./globals.css";
import { Roboto_Slab } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import { ThemeContextProvider } from "@/context/theme";

// const inter = Inter({ subsets: ["latin"] });
const font = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-slate-50  sm:ml-80 mt-16 text-gray-700`}>
        <ThemeContextProvider>
          <Sidebar />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
